@blogger_clone_HostAddress = http://localhost:5002
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmExMDllMy1mYmZlLTQ4MGYtYjgzMC03ODQwZTU0Nzg4MDYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NzI5OTQyNywiaXNzIjoiYmxvZ2dpbmctYXBwIiwiYXVkIjoiVXNlciJ9.U3tGziL8vGooNAbOybfVuSfjFAB3iydQST3Yd_Xz3Ec

GET {{blogger_clone_HostAddress}}/weatherforecast/
Accept: application/json

### User Register

POST {{blogger_clone_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "string123"
}

### User Login

POST {{blogger_clone_HostAddress}}/api/v1/auth/login
Content-Type:  application/json

{
    "usernameoremail": "admin@example.com",
    "password": "string123"
}

### Create Blog

GET {{blogger_clone_HostAddress}}/api/v1/blog/create-domain
Authorization: Bearer {{token}}

### Get All Blog (User)

GET {{blogger_clone_HostAddress}}/api/v1/blog/list-all
Authorization: Bearer {{token}}

### Delete Blog

DELETE {{blogger_clone_HostAddress}}/api/v1/blog
Authorization: Bearer {{token}}

### Delete Blog (ADMIN)

DELETE {{blogger_clone_HostAddress}}/api/v1/admin/blog/1c9ce8c9-9921-46ca-8053-59c31d04b7cc
Authorization: Bearer {{token}}

### Get all Blog (Admin)

GET {{blogger_clone_HostAddress}}/api/v1/admin/blog/
Authorization: Bearer {{token}}
